version: "3.5"

services:
  postfix:
    image: postfix-docker
    container_name: postfix
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env
    networks:
      - mail

networks:
  mail:
    name: mail